name: Build and Deploy Hugo to FTP

on:
  schedule:
    - cron: '0 0 * * *'  # Menjadwalkan deploy setiap tengah malam
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Run Hugo
        run: hugo --minify

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "ftp-server011.web.2nt.com"  # Sesuaikan dengan server FTP Anda
          username: "spruchexsc"
          password: "d0!p0#&tlP"
          local-dir: ./public/
          server-dir: /
          timeout: 600  # Timeout lebih panjang
          retries: 5  # Mengulang hingga 5 kali jika gagal
          retry-delay: 10  # Delay antara percobaan ulang (10 detik)
          log-level: verbose  # Aktifkan log untuk informasi lebih detail
          passive: true  # Mode pasif, lebih stabil dalam banyak kasus
